# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slv < Formula
  desc ""
  homepage "https://savesecrets.org/slv"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/savesecrets/slv-release/releases/download/v0.0.9/slv-release_0.0.9_darwin_amd64.zip"
      sha256 "03884fa6806523bd0c5c6f9e44bcb5ab975c74c620289014f1a6ae28bbc3af63"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/savesecrets/slv-release/releases/download/v0.0.9/slv-release_0.0.9_darwin_arm64.zip"
      sha256 "260e6ed7a01cf5c8500996574cbb79c47ac51a77dfb2d28bd463282e946d9364"

      def install
        bin.install "slv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/savesecrets/slv-release/releases/download/v0.0.9/slv-release_0.0.9_linux_arm64.zip"
      sha256 "6d165f00cf1192dc87b5b4df02af379c13e84aa88b3ed96f0400dafcdec14e4b"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/savesecrets/slv-release/releases/download/v0.0.9/slv-release_0.0.9_linux_amd64.zip"
      sha256 "da3a1329d4110a3491d8b80545a4c158855ab76405e54e3222a2131c47828751"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/savesecrets/slv-release/releases/download/v0.0.9/slv-release_0.0.9_linux_armv6.zip"
      sha256 "2a173233f0fc4c7b3d037717d6fb3b42dcbee76691c27eecf5b288d800f411ac"

      def install
        bin.install "slv"
      end
    end
  end
end
